version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - MYSQL_ROOT_PASSWORD=EaseEG@2050
      - ACTIVE_PROFILE=prod
  db:
    container_name: bookstore_db
    image: mysql:8.0.32
    environment:
      - MYSQL_ROOT_PASSWORD=EaseEG@2050
      - MYSQL_DATABASE=BookstoreDB
    volumes:
      - db-data:/var/lib/mysql
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8090:8090"
    depends_on:
      - app
    links:
      - app
volumes:
  db-data:
